/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.cuarteldebomberos.vistas;

import com.mycompany.cuarteldebomberos.controlador.BrigadaData;
import com.mycompany.cuarteldebomberos.modelo.Brigada;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author br1st
 */
public class BrigadaViewListarLibres extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form BrigadaViewListarLibres
     */
    public BrigadaViewListarLibres() {
        initComponents();
        armarCabecera();
        llenarTablaConBrigadasLibres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtBrigadasLibres = new javax.swing.JTable();

        jtBrigadasLibres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtBrigadasLibres);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void armarCabecera() {
        modelo.addColumn("codBrigada");
        modelo.addColumn("nombre_br");
        modelo.addColumn("libre");
        modelo.addColumn("nro_cuartel");
        jtBrigadasLibres.setModel(modelo);
    }
    
    private void llenarTablaConBrigadasLibres(){
        List<Brigada> brigadasLibres = MainMenu.consultaBrigadasLibres();
        for(Brigada brigada:brigadasLibres) {
            Object[] rowData = {brigada.getCodBrigada(), brigada.getNombre_br(), brigada.getLibre(), brigada.getFKnro_cuartel()};
            modelo.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtBrigadasLibres;
    // End of variables declaration//GEN-END:variables
}
