/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cuarteldebomberos.vistas;

import com.mycompany.cuarteldebomberos.controlador.BrigadaData;
import com.mycompany.cuarteldebomberos.modelo.Brigada;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author br1st
 */
public class MainMenu extends javax.swing.JFrame {
    private static BrigadaData bd = new BrigadaData();
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCreacion = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jmBusqueda = new javax.swing.JMenu();
        jmBrigadas = new javax.swing.JMenu();
        jmiBuscarPorNombre = new javax.swing.JMenu();
        jmiListarLibres = new javax.swing.JMenuItem();
        jmiListarAsignadas = new javax.swing.JMenuItem();
        jmiListarTodas = new javax.swing.JMenuItem();
        jmModificar = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 500));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jmCreacion.setText("Creacion");

        jMenuItem5.setText("Brigadas");
        jmCreacion.add(jMenuItem5);

        jMenuItem6.setText("Bomberos");
        jmCreacion.add(jMenuItem6);

        jMenuItem7.setText("Siniestros");
        jmCreacion.add(jMenuItem7);

        jMenuItem8.setText("Cuarteles");
        jmCreacion.add(jMenuItem8);

        jMenuBar1.add(jmCreacion);

        jmBusqueda.setText("Busqueda/Listado");

        jmBrigadas.setText("Brigadas");

        jmiBuscarPorNombre.setText("Buscar Por Nombre");
        jmBrigadas.add(jmiBuscarPorNombre);

        jmiListarLibres.setText("ListarLibres");
        jmiListarLibres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarLibresActionPerformed(evt);
            }
        });
        jmBrigadas.add(jmiListarLibres);

        jmiListarAsignadas.setText("ListarAsignadas");
        jmiListarAsignadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarAsignadasActionPerformed(evt);
            }
        });
        jmBrigadas.add(jmiListarAsignadas);

        jmiListarTodas.setText("ListarTodas");
        jmiListarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarTodasActionPerformed(evt);
            }
        });
        jmBrigadas.add(jmiListarTodas);

        jmBusqueda.add(jmBrigadas);

        jMenuBar1.add(jmBusqueda);

        jmModificar.setText("Modificar/Eliminar");

        jMenuItem9.setText("Brigadas");
        jmModificar.add(jMenuItem9);

        jMenuItem10.setText("Bomberos");
        jmModificar.add(jMenuItem10);

        jMenuItem11.setText("Siniestros");
        jmModificar.add(jMenuItem11);

        jMenuItem12.setText("Cuarteles");
        jmModificar.add(jMenuItem12);

        jMenuBar1.add(jmModificar);

        jMenu1.setText("Radar/LogisticaDeBrigadas");

        jMenuItem13.setText("Calcular Distancias y Logistica de Brigadas");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuBar1.add(jMenu1);

        jmSalir.setText("Salir");
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiListarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarTodasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BrigadaViewListarTodas bvlt = new BrigadaViewListarTodas();
        bvlt.setVisible(true);
        escritorio.add(bvlt);
        escritorio.moveToFront(bvlt);
    }//GEN-LAST:event_jmiListarTodasActionPerformed

    private void jmiListarLibresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarLibresActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BrigadaViewListarLibres bvll = new BrigadaViewListarLibres();
        bvll.setVisible(true);
        escritorio.add(bvll);
        escritorio.moveToFront(bvll);
    }//GEN-LAST:event_jmiListarLibresActionPerformed

    private void jmiListarAsignadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarAsignadasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BrigadaViewListarAsignadas bvla = new BrigadaViewListarAsignadas();
        bvla.setVisible(true);
        escritorio.add(bvla);
        escritorio.moveToFront(bvla);
    }//GEN-LAST:event_jmiListarAsignadasActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        LogisticaView lv = new LogisticaView();
        lv.setVisible(true);
        escritorio.add(lv);
        escritorio.moveToFront(lv);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    public static List<Brigada> consultaBrigadasLibres() {
        List<Brigada> brigadas = bd.listarTodasLasBrigadas();
        List<Brigada> brigadasLibres = new ArrayList<>();
        for(Brigada brigada:brigadas){
            if(brigada.getLibre()){
                brigadasLibres.add(brigada);
            }
        }
        return brigadasLibres;
    }
    
    public static List<Brigada> consultaBrigadasOcupadas() {
        List<Brigada> brigadas = bd.listarTodasLasBrigadas();
        List<Brigada> brigadasOcupadas = new ArrayList<>();
        for(Brigada brigada:brigadas){
            if(!brigada.getLibre()){
                brigadasOcupadas.add(brigada);
            }
        }
        return brigadasOcupadas;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jmBrigadas;
    private javax.swing.JMenu jmBusqueda;
    private javax.swing.JMenu jmCreacion;
    private javax.swing.JMenu jmModificar;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenu jmiBuscarPorNombre;
    private javax.swing.JMenuItem jmiListarAsignadas;
    private javax.swing.JMenuItem jmiListarLibres;
    private javax.swing.JMenuItem jmiListarTodas;
    // End of variables declaration//GEN-END:variables
}
